cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
    
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('warehouse/', include('warehouse.urls', namespace='warehouse')),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/',include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('charge/', views.charge, name='charge'),  # new
    path('', views.Payment.as_view(), name='Payment'),

]

shop/urls.py
from django.urls import path
from . import views
            
app_name='shop'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

warehouse/urls.py
from django.urls import path
from . import views

app_name = 'warehouse'

urlpatterns = [
    path('', views.searchproducts, name='searchproducts'),
    path('shopkeeper/',views.shopkeeper_view,name='shopkeeper_view'),

]

warehouse/models.py
from django.db import models
from shop.models import Product

ZONE_CHOICES = (
    ('RED ZONE', 'R'),
    ('ORANGE ZONE', 'O'),
    ('GREEN ZONE', 'G')
)

CITY_CHOICES = (
    ('Bhim Colony', 'Bhim Colony'),
    ('Basai Enclave-2', 'Basai Enclave-2'),
    ('Chandan Vihar', 'Chandan Vihar'),
    ('Ganga Vihar', 'Ganga Vihar'),
    ('Sai Kunj', 'Sai Kunj'),
    ('Shri Ram Colony', 'Shri Ram Colony'),
    ('Amanpura Colony', 'Amanpura Colony'),
    ('Patel Nagar Ext', 'Patel Nagar Ext'),
    ('Shiv Nagar', 'Shiv Nagar'),
    ('Vikas Nagar', 'Vikas Nagar'),
    ('Basai Enclave Ext', 'Basai Enclave Ext'),
    ('Krishna Nagar', 'Krishna Nagar'),
    ('Surya Vihar', 'Surya Vihar'),
    ('Ashok Vihar', 'Ashok Vihar'),
    ('Rajeev colony', 'Rajeev colony'),
    ('Nihal Vihar', 'Nihal Vihar'),
    ('Mayur Kunj', 'Mayur Kunj'),
    ('Ryan Enclave', 'Ryan Enclave'),
    ('Shyam Kunj', 'Shyam Kunj'),
    ('Shanti Kunj', 'Shanti Kunj'),
    ('Mohan Nagar', 'Mohan Nagar'),
    ('Vatika Kunj', 'Vatika Kunj'),
    ('Defense Enclave', 'Defense Enclave'),
)

SLOT_CHOICES = (
    ('Morning Slot', 'Morning  {8 am - 12 pm}'),
    ('Noon Slot', 'Noon {12 pm - 7 pm}'),
    ('Night Slot', 'Night {7 pm - 11 pm}'),
)


class Warehouse(models.Model):
    location = models.CharField(
        max_length=100, choices=CITY_CHOICES, null=True)
    zone = models.CharField(max_length=30, choices=ZONE_CHOICES, null=True)
    loc_x = models.DecimalField(max_digits=10, decimal_places=6)
    loc_y = models.DecimalField(max_digits=10, decimal_places=6)
    time_slot = models.CharField(max_length=100, choices=SLOT_CHOICES, null=False, default='Noon {12 pm - 7 pm}')
    delivery_boy=models.CharField(max_length=50,null=True)
    contact=models.CharField(max_length=10,null=True)

    def __str__(self):
        return self.location


class KeyVal(models.Model):
    locname = models.ForeignKey(Warehouse, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

warehouse/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, get_list_or_404
from django.contrib.admin.views.decorators import staff_member_required
from users.models import User
from orders.models import Order, OrderItem
from .models import Warehouse, KeyVal
from math import sin, cos, sqrt, atan2, radians, pi
import json

cities = {
    "Bhim Colony": "23.02579,72.58727",
    "Basai Enclave-2": "12.97194,77.59369",
    "Chandan Vihar": "13.08784,80.27847",
    "Ganga Vihar": "24.879999,74.629997",
    "Sai Kunj": "26.263863, 73.008957",
    "Shri Ram Colony": "21.250000 ,81.629997",
    "Amanpura Colony": "24.882618,72.858894",
    "Patel Nagar Ext": "25.771315,73.323685",
    "Shiv Nagar": "28.65195,77.23149",
    "Vikas Nagar": "17.38405,78.45636",
    "Basai Enclave Ext": "26.46523,80.34975",
    "Krishna Nagar": "22.56263,88.36304",
    "Surya Vihar": "19.07283,72.88261",
    "Ashok Vihar": "16.994444 , 73.300003",
    "Rajeev colony": "18.51957,73.85535",
    "Nihal Vihar": "21.19594,72.83023",
    "Mayur Kunj": "26.264776, 82.072708",
    "Ryan Enclave": "26.839281,80.923133",
    "Shyam Kunj": "25.615379,85.101027",
    "Shanti Kunj": "22.717736,75.85859",
    "Mohan Nagar": "22.299405,73.208119",
    "Vatika Kunj": "23.254688,77.402892",
    "Defense Enclave": "11.005547,76.966122",
}


def getDistanceFromLatLonInKm(lat1, lon1, lat2, lon2):
    R = 6371
    dLat = deg2rad(lat2 - lat1)
    dLon = deg2rad(lon2 - lon1)
    a = sin(dLat / 2) * sin(dLat / 2) + cos(deg2rad(lat1)) * \
        cos(deg2rad(lat2)) * sin(dLon / 2) * sin(dLon / 2)
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    d = R * c
    return d


def deg2rad(deg):
    return deg * (pi / 180)


def searchproducts(request):
    fcart = OrderItem.objects.filter(order_id=request.session['order.id'])
    totalitems = OrderItem.objects.filter(order_id=request.session['order.id']).count()
    warehouses = Warehouse.objects.all()
    user_order = get_object_or_404(Order, id=request.session['order.id'])
    user_loc = user_order.city
    print(user_loc)
    lat1, lon1 = cities.get(user_loc).split(",")
    dis = {}
    count = 0
    extra = 0

    for item in fcart:
        min_dist = 10000000000.00
        nearest_war = ''
        for wh in warehouses:
            try:
                wareitem = get_object_or_404(
                    KeyVal, locname=wh, product=item.product)
            except:
                continue
            if (wareitem.quantity >= item.quantity):
                if user_loc == wh.location:  # Skip distance calculation
                    min_dist = 0
                    nearest_war = wh
                    break
                lat2 = wh.loc_x
                lon2 = wh.loc_y
                lat1, lon1, lat2, lon2 = float(lat1), float(lon1), float(lat2), float(lon2)
                dist = getDistanceFromLatLonInKm(lat1, lat2, lon1, lon2)
                #print(item.product.name)
                #print(wh.location)
                #print(dist)
                if (dist <= min_dist):
                    min_dist = dist
                    nearest_war = wh
                else:
                    continue
                #print(min_dist)
            else:
                continue
        if(nearest_war):
            item.selected_shop=nearest_war
            item.save()
        else:
            user_order.total_price=user_order.total_price-item.get_cost()
            print(user_order.total_price)

        if nearest_war and nearest_war.time_slot==item.order.time_slot:
            count=count+1
        dis[item.product.name] = nearest_war

    #print(count)
    #Adding extra charge to the user's account
    if count < (totalitems/2):
        extra = 50
    

    return render(request, 'warehouse/delivery_area.html', {'waredis': dis,'extra':extra,'user_order':user_order})

@staff_member_required
def shopkeeper_view(request):
    cur_user=request.user
    items=OrderItem.objects.filter(selected_shop=cur_user.profile.warehouse)
    return render(request,'warehouse/shopkeeper.html',{ 'items':items})

warehouse/templates/warehouse/delivery_area.html
{% extends "shop/base.html" %}
{% block content %}
<div class="container">
   <div class="row mb-5">
          <div class="col-md-12">
              <div class="p-3 p-lg-5 border">

                <table class="table site-block-order-table mb-5">
                    <thead>
                      <tr>
                        <th class="product-name">Product</th>
                        <th class="product-price">Warehouse</th>
                        <th class="product-quantity">Zone</th>
                        {% comment %} <th class="product-total">Total</th> {% endcomment %}
                      </tr>
                    </thead>
                    <tbody>
                     {% for key, value in waredis.items %}
                      <tr>
                        <td class="product-name"> <h3 class="h5 text-black">{{ key}}</h3></td>
                        <td>
                            <h3 class="h5 text-black">
                                  {% if value %}
                                    {{ value.location }}
                                  {% else %}
                                    Sorry this item is currently unavailable
                                  {% endif %}
                            </h3>
                        </td>
                        <td>
                                 <h3 class="h5" >
                                     {% if value.zone == 'ORANGE ZONE' %}
                                         <div style="color:orange;">
                                           {{ value.zone }}
                                         </div>
                                     {% endif %}
                                     {% if value.zone == 'RED ZONE' %}
                                         <div style="color:red;">
                                           {{ value.zone }}
                                         </div>
                                     {% endif %}
                                     {% if value.zone == 'GREEN ZONE' %}
                                         <div style="color:green;">
                                           {{ value.zone }}
                                         </div>
                                     {% endif %}
                                 </h3>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                </table>
                {% if extra %}
                 <p style="color:red;">You will have to pay extra charge of Rs 50 for delivery according to your time</p>
                  <p style="color:red;">Your total money is <span style="color:black;">{{ user_order.total_price }}+50 = {{user_order.total_price|add:"50"}}</span></p>
              {% else %}
                  <p style="color:green;">You don't need to pay extra</p>
              {% endif %}

        </div>

         <div class="container">
            <div class="row">
          <div class="col-3 ">
              <a href="{% url 'shop:product_list' %}" ><button  class="btn btn-primary btn-sm btn-block mt-3">Continue Shopping</button></a>
          </div>
          <div class="col-3">
           <a href="{% url 'payment:Payment' %}" ><button  class="btn btn-outline-primary btn-sm btn-block">Continue Payment</button></a>
       </div>
        </div>
         </div>
        </div>
      </div>

{% endblock %}

warehouse/templates/warehouse/shopkeeper.html
{% extends "shop/base.html" %}
{% block content %}
<div class="container">
<h4 style="color:hsl(120, 100%, 25%);text-align:center;font-weight: 600;padding-bottom: 20px;">Paid Orders Summary</h4>
<table class="table" style="border: 1px solid green;">
  <thead style="background-color:hsl(120, 100%, 25%)">
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Delivery Area</th>
      <th scope="col">Delivered</th>
    </tr>
  </thead>
  <tbody>
  {% for itm in items %}
   {% if itm.order.paid %}
    {% with uorder=itm.product %}
    <tr >
      <td>{{ uorder.name}}</td>
      <td>{{ itm.quantity}}</td>
      <td>{{ itm.order.city}}</td>
      <td>   </td>
    </tr>
    {% endwith %}
   {% endif %}
  {% endfor %}
  </tbody>
</table>
<h4 style="color:red;text-align:center;font-weight: 600;padding-bottom: 20px;">Unpaid Orders</h4>
<table class="table" style="border: 1px solid red;">
  <thead style="background-color:red">
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Delivery Area</th>
      <th scope="col">Cancelled</th>
    </tr>
  </thead>
  <tbody>
  {% for itm in items %}
   {% if itm.order.paid == False%}
    {% with uorder=itm.product %}
    <tr>
      <td>{{ uorder.name}}</td>
      <td>{{ itm.quantity}}</td>
      <td>{{ itm.order.city}}</td>
      <td> </td>
    </tr>
    {% endwith %}
   {% endif %}
  {% endfor %}
  </tbody>
</table>
</div>

{% endblock %}